Feature/330 animated hero icons
Tonomy-Foundation/Tonomy-Foundation-Next-Website pull request #244
Opened 2023-08-09 13:23 UTC by HaseebUllahAbbasi

2023-08-09 16:18 UTC, theblockstalk requested changes

2023-08-09 16:18 UTC, theblockstalk commented on pnpm-lock.yaml
this file should not be included I think

2023-08-09 16:18 UTC, theblockstalk commented on pages/_document.js
> +          <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
should this change like this?

2023-08-09 16:18 UTC, theblockstalk commented on components/Home/MainBanner.js
> +    zIndex: -10,
this is the desired design for how it blends to the background.
https://drive.google.com/file/d/1JOMmk01skQTtlC7cRI2nvDajPuKJLvlS/view

I don't know how to do this but some kind of "radial gradient" sounds right. See https://stackoverflow.com/questions/32059991/how-to-make-a-radial-gradient-with-transparency-in-css

2023-08-09 16:18 UTC, theblockstalk commented on components/Home/MainBanner.js
animation does not match design https://drive.google.com/file/d/1JOMmk01skQTtlC7cRI2nvDajPuKJLvlS/view

- lightblue background (img_5) currently rotates 180 degrees and should only be 90 degrees
- padlock (img_0) and padlock top (img_3) should both slide in from top at same time. they also shouldn't zoom into frame at all.
- padlock top (img_3) should vertical flip from left to right after it slides in from top
- profile icon (img_2), then "ID" svg, then tonomy logo (img_1) should slide up into the middle of the circle, and then out, in order and replacing the previous image

this logic is all inside the demo/data.html file so you could copy most of it from there. What you have done is much cleaner and more controllable so if you can get it does with your own CSS and .js that is better. But i suggest the easiest strategy.

2023-08-10 08:22 UTC, HaseebUllahAbbasi commented on pages/_document.js
> +          <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
Yeah, i was being warned

2023-08-10 08:23 UTC, HaseebUllahAbbasi commented on pnpm-lock.yaml
I used this svg as an image here

2023-08-14 19:13 UTC, HaseebUllahAbbasi commented on pnpm-lock.yaml
that is removed ..

2023-08-16 08:20 UTC, theblockstalk commented on .gitignore
> +# pnpm-lock.yaml
remove comment

2023-08-16 08:20 UTC, theblockstalk commented on components/Home/MainBanner.js
> +import animatedData from "../assets/animated.json"; // Adjust the path as needed
lets call it assets/home/main-banner.js

2023-08-16 08:20 UTC, theblockstalk commented on components/Home/MainBanner.js
> +const AnimatedHeroImage = () => {
add new lines before and after root level constants, styles, functions or functional components

2023-08-17 07:40 UTC, theblockstalk approved these changes

2023-08-17 07:40 UTC, merged